"""Prompt templates for evaluator LLM-as-judge passes."""

# This prompt is used to classify each generated S2R step as either a correct
# step (CS) or an extra step (ES) relative to the ground-truth S2Rs.
S2R_JUDGE_PROMPT = """# Task Summary

You are an experienced Android application developer. Your task is to **evaluate the quality of automatically generated steps to reproduce (S2Rs) of a bug** in an Android app by **comparing them to human-written (ground truth) S2Rs**. Use the evaluation metrics described below to perform this comparison.

---

# You are provided with:

- **Evaluation metrics** with detailed definitions.  
- A list of **ground truth S2Rs**, each with a unique ID and description.  
- A list of **generated S2Rs**, each with a unique ID and description.

---

# Evaluation Metrics

1. **Correct Step (CS):** A generated step matches a ground truth step if the actions they describe are **semantically equivalent**, even if wording or IDs differ. 
   - If a generated step indicates that an action should be performed **_n_ times** (either by repeating the step or explicitly stating the repetition), and the same step appears **_n_ times** in the ground truth, then the **Correct Step (CS) count should be _n_**.   
2. **Missing Step (MS):** A ground truth step that has **no semantically equivalent step** in the generated list.  
3. **Extra Step (ES):** A generated step that does **not match any** ground truth step.  
   - If a generated step appears more times than it does in the ground truth, count the **additional instances** as extra steps (ES).

---

# Matching Criteria

1. Use the **natural language description** as the primary basis for matching.
  - Focus on the **core action and user intent**, not exact phrasing or additional explanatory text.
  - Consider actions using different but interchangeable terms (e.g., "Tap" vs. "Click", "Press" vs. "Select") as equivalent.
  - Ignore additional context or explanations in a step (e.g., "to apply the changes", "to continue", "to grant permissions") **if the main action remains unchanged**.
  - For example:
    - `"Open the Family Finance application"` matches `"Open App"`.
    - `"Tap the 'OK' button to apply the changes"` matches `"Click OK"`.
    - `"Click the floating button"` matches `"Tap the FAB"`.
2. Steps with matching IDs are **definitely equivalent**.
3. Steps with different IDs can still be equivalent if they represent the **same user interaction**.
4. When in doubt, match based on **semantic similarity** and **user intention**, not on UI labels or verbosity.
5. If a generated step contains additional descriptive context (e.g., "to apply the changes"), ignore it when comparing if it doesn't alter the user action being performed.

---

# Instructions

1. For each step in the **generated S2Rs**, try to find a matching step in the **ground truth S2Rs** following the **Matching Criteria**.
2. Assign either CS or ES labels to each **generated S2Rs** according to their definition.
3. Do not need to assign an MS label to the **generated S2Rs**.
4. Return your response in JSON format (see the **Response Format** below), with a top-level `"steps"` field containing one dictionary per generated step. Each dictionary must include:
  - "generated_step": one generated step in one dictionary
  - "label": the assigned label of that generated step, i.e., either CS or ES
  - "matched_gt_step": if the label is CS, then the matched ground truth step; blank otherwise
5. **Do not include any explanation or notes in the output.**

---

# Ground Truth S2Rs
{ground_truth_s2rs}

---

# Generated S2Rs
{generated_s2rs}

---

# Response Format

Return only the structured output matching the provided schema.

**Do not include anything else in the response.**
"""


# This prompt is used to assign a quality label to each OB/EB information
# element by comparing the generated extraction against ground truth.
INFO_ELEMENTS_JUDGE_PROMPT = """# Task Summary

You are an experienced Android application developer. Your task is to **evaluate the quality** of the **Information Elements** for **Observed Behavior (OB)** and **Expected Behavior (EB)** in Android app bug reports generated by an automated approach.
You will compare them against **human-created ground truth Information Elements** and assign the appropriate **Quality Labels**.

---

# You are provided with:

- Definitions of the **Information Elements** to evaluate.
- **Quality Labels** with definitions.
- Human-created ground truth **Information Elements** (with OB and EB).
- Approach-generated **Information Elements** (with OB and EB).

---

# Definition of the Information Elements

- **Buggy Behavior** (What buggy behavior is observed by the user?): The specific buggy behavior (i.e., the problem) reported in the bug.
- **Triggering GUI Interactions** (What application interaction(/s) triggers the bug?): The user interaction(/s) on the application that triggers the bug.
- **Triggering Screen References** (Which application screen causes the bug and/or where the bug was observed?): The application screen where performing the interaction causes the bug and/or the screen where the bug was observed.
- **Correct Behavior** (What application behavior is expected by the user?): The specific correct application behavior that should happen instead of the buggy behavior.

---

# Quality Labels

- **Correct**: The **generated Information Element** contains the meaning of the **ground truth Information Element**, even if it uses different wording, synonyms, or includes extra contextual details. As long as the **core meaning of the ground truth is present**, it is Correct.
- **Incomplete**: The **generated Information Element** contains part of the **ground truth Information Element** but leaves out an essential detail, making it only a partial match.
- **Ambiguous**: The **generated Information Element** is vague, unclear, or can be interpreted in multiple ways compared to the **ground truth Information Element**.
- **Missing**: The **generated Information Element** does not contain any information (e.g., “N/A”).
- **Incorrect**: The **generated Information Element** is completely different from the ground truth.

---

# Instructions

1. Analyze each **generated Information Element**, including the OB and EB descriptions, one by one.
2. Compare each **generated Information Element** with the **ground truth Information Element** based on **semantic meaning**, not exact wording.
   - Minor rewordings, expansions, or equivalent variations (e.g., different phrasing, broader/narrower scope, or navigation vs. selection actions) are acceptable as long as the **core meaning** remains the same.
3. Assign each **generated Information Element** a quality label: **Correct, Incomplete, Ambiguous, Missing, or Incorrect**, based on the definitions.
4. **Do not include any explanation or notes in the output.**

---

# Ground Information Elements with OB and EB
{ground_truth_info_elements}

---

# Generated Elements with OB and EB
{generated_info_elements}

---

# Response Format
Return only the structured output matching the provided schema.

**Do not include anything else in the response.**
"""
