"""init

Revision ID: a2ee49830337
Revises: 
Create Date: 2026-02-11 09:06:05.326508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ee49830337'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug_id', sa.Integer(), nullable=False),
    sa.Column('application_name', sa.String(), nullable=False),
    sa.Column('gui_graph', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bug_id')
    )
    op.create_table('screen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug', sa.Integer(), nullable=False),
    sa.Column('state_hash', sa.String(), nullable=False),
    sa.Column('full_state_line', sa.String(), nullable=False),
    sa.Column('image_uri', sa.String(), nullable=False),
    sa.Column('screen_description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bug'], ['bug.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_hash', 'image_uri')
    )
    op.create_table('transition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug', sa.Integer(), nullable=False),
    sa.Column('transition_hash', sa.String(), nullable=False),
    sa.Column('full_transition_line', sa.String(), nullable=False),
    sa.Column('image_uri', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bug'], ['bug.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transition_hash', 'image_uri')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transition')
    op.drop_table('screen')
    op.drop_table('bug')
    # ### end Alembic commands ###
