"""drop screen and transition add bug.screen_descriptions

Revision ID: e0ba5877033a
Revises: a2ee49830337
Create Date: 2026-04-05 13:37:50.767451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ba5877033a'
down_revision: Union[str, Sequence[str], None] = 'a2ee49830337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screen')
    op.drop_table('transition')
    op.add_column('bug', sa.Column('screen_descriptions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bug', 'screen_descriptions')
    op.create_table('transition',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bug', sa.INTEGER(), nullable=False),
    sa.Column('transition_hash', sa.VARCHAR(), nullable=False),
    sa.Column('full_transition_line', sa.VARCHAR(), nullable=False),
    sa.Column('image_uri', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['bug'], ['bug.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transition_hash', 'image_uri')
    )
    op.create_table('screen',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bug', sa.INTEGER(), nullable=False),
    sa.Column('state_hash', sa.VARCHAR(), nullable=False),
    sa.Column('full_state_line', sa.VARCHAR(), nullable=False),
    sa.Column('image_uri', sa.VARCHAR(), nullable=False),
    sa.Column('screen_description', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['bug'], ['bug.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_hash', 'image_uri')
    )
    # ### end Alembic commands ###
